### ISSUE TITLE
Feature request: add support for Redis password authentication

### ISSUE THREAD

**Issue by itamarhaber** [vy/log4j2-redis-appender#1]
When configured (highly-advised!) with `requirepass`, Redis requires the client to send an `AUTH` request after connecting to allow any other further operations. As Jedis supports this, it shouldn't be hard to add this to the appender's configuration.

Looking ahead, you may want to allow configuring the appender with existing Jedis pools, connections and whatnot instead of making them inside.

**Comment by vy** [comment]
Released version 0.2, should show up in Maven Central in a couple of hours. This release replaces `Jedis` client with its thread-safe alternative `JedisPool`. Further, added support for password too.
