### ISSUE TITLE
Redis username

### ISSUE THREAD

**Issue by rmarticaba** [vy/log4j2-redis-appender#132]
Hi!

Thanks for bringing this tool.

I was trying to use it to store my application logs into redis, but I bumped into an issue when trying to use a username different from `default`, as it is not configurable. I did small changes to allow to use a different username and configure it through log4j2.xml and I'd like to contribute those changes if you see them ok, but I lack permissions to push a new branch with the proposed changes.

Please share if that is something I can contribute with.

**Comment by vy** [comment]
@rmarticaba, sounds like a good idea. Please submit a PR. I would appreciate it if you can

* add tests
* stick to the coding style in places where you touch

**Comment by rmarticaba** [comment]
Thanks @vy,

I submitted the PR with the changes and testing (I adapted existing tests to use the new username / password pair)

**Comment by vy** [comment]
Fixed by #134.
