### ISSUE TITLE
How to switch between Redis dbs?

### ISSUE THREAD

**Issue by RickoNoNo3** [vy/log4j2-redis-appender#16]
As we know Redis has a concept called db, which provides 16(by default) different storage spaces seperated from each other. I'm using 0-3 of them, and I want my Log4J2 append its logs to the 3rd.

I can't find a configuration property in this library's doc, does it supports?

**Comment by vy** [comment]
@RickoNoNo3, `log4j2-redis-appender` internally uses [jedis](/redis/jedis), the official Java client for Redis, for interacting with Redis. There I don't see the mention of a feature similar to what you are describing. Mind providing some pointers for that feature, please?

**Comment by RickoNoNo3** [comment]
I finally find something about it in the code.

https://github.com/vy/log4j2-redis-appender/blob/45c207ffb69fa64dbd155afe7b42232b64d4208a/appender/src/main/java/com/vlkan/log4j2/redis/appender/RedisAppender.java#L227-L260

The parameter is set to 0 (L243 and L253). It may be customizable.

**Comment by vy** [comment]
@RickoNoNo3, got it, thanks! I will try to add that.

**Comment by vy** [comment]
@RickoNoNo3, I have added `database` parameter to the appender in the most recent `0.11.0-SNAPSHOT` release. Would you mind confirming the fix, please?

**Comment by RickoNoNo3** [comment]
Nice work! It works fine in my SpringBoot project. I also tried to fork and modify the tests of this library, the `RedisAppenderTest` passed in database 10. But Embedded Redis Server was not fully effective on my Mac, so other two had not past yet. I don't think it is the reason for the Appender. 

In brief, well done!

**Comment by vy** [comment]
Thanks for confirming the fix! I am trying to overhaul the project. I have one more (graceful shutdown) bug in my list to process. I will probably wrap up my work this week and cut a new release. I will let you know of the new release here via dropping a comment.

**Comment by vy** [comment]
@RickoNoNo3, I have just released 0.11.0, enjoy while it is still hot! :coffee:
