### ISSUE TITLE
RedisThrottler should not use a non-daemon Thread

### ISSUE THREAD

**Issue by t9t** [vy/log4j2-redis-appender#3]
The `RedisThrottler` creates a `Thread` to periodically flush. However this thread does not have `daemon` set, meaning it's a non-daemon thread. This means in turn that if the JVM wants to shut down, and these are the only threads still running, the JVM will not shut down (it will only shut down when the only remaining threads are daemon threads).

This can interact badly with other frameworks, eg. when Log4j2 is managed using Spring Boot, and the logger context closed when the Spring context is shut down. Spring Boot will close the context in a shutdown hook, but the shutdown hook will not be triggered as there are still non-daemon threads running.

This can be solved by calling `setDaemon(true)` on the `flushTrigger` thread in `RedisThrottler`.

**Comment by vy** [comment]
`v0.5` should momentarily appear in the Maven Central repositories. Thanks for the report @t9t!
