### ISSUE TITLE
Using Trace Id as a key instead of a static key

### ISSUE THREAD

**Issue by dawityifter** [vy/log4j2-redis-appender#7]
This is not an issue per se but I am wondering if it is possible to have a dynamic key (say a trace id that I get from MDC (Sleuth).

**Comment by vy** [comment]
Hey @dawityifter! Would you mind providing some more context, please? I will really appreciate an example demonstrating what is the current state and what do you want instead.

**Comment by dawityifter** [comment]
Thanks for the response @vy The use case I am faced with is to use a Redis appender and log certain data to redis. And send real time notification to subscribers. So we use sleuth and each http request will have some kind of trace id that the subscribers will listen to. 
 ```
<RedisAppender name="REDIS"
                       key="**log4j2-messages**"
                       host="localhost"
                       port="6379">
``` The key here is static and I would like to see if creating a new key for each traceId would be possible. I hope I have made my request clear.

**Comment by vy** [comment]
@dawityifter, I am not familiar with Sleuth, but assuming you have a `traceId=k2X8d2Q` entry in your MDC, why don't you just use `"traceId": "${json:mdc:traceId}"` in your template? Why do you need to create a dynamic key, rather than just exposing the value you need through a fixed key?
